-- Migration: 20260331000000_add_reports_schema.sql
-- Description: Creates the full reports domain schema.
--   Includes configuration tables (task_templates, stock_items, report_sections),
--   the reports table, and all three snapshot+response table pairs.
--   Also adds the FK constraint on the pre-existing shifts.report_id column.
--
-- Rollback:
--   ALTER TABLE public.shifts DROP CONSTRAINT IF EXISTS shifts_report_id_fkey;
--   DROP TABLE IF EXISTS
--     public.report_section_responses,
--     public.report_section_items,
--     public.report_stock_entries,
--     public.report_stock_items,
--     public.report_task_completions,
--     public.report_task_items,
--     public.reports,
--     public.report_sections,
--     public.stock_items,
--     public.task_template_items,
--     public.task_templates
--   CASCADE;
--   DROP TYPE IF EXISTS public.report_status;


-- ─── Status enum ─────────────────────────────────────────────────────────────

CREATE TYPE public.report_status AS ENUM ('in_progress', 'completed');


-- ─── Part I configuration: task templates ────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.task_templates (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text        NOT NULL,
  is_active  boolean     NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- Enforces "at most one active template at any time" at the DB layer.
-- Application must set is_active = false on the current active template
-- before activating a new one (or use an UPDATE that toggles both in one txn).
CREATE UNIQUE INDEX task_templates_one_active_idx
  ON public.task_templates (is_active)
  WHERE is_active = true;

CREATE TABLE IF NOT EXISTS public.task_template_items (
  id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint  NOT NULL REFERENCES public.task_templates(id) ON DELETE CASCADE,
  position    integer NOT NULL CHECK (position > 0),
  description text    NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT timezone('utc', now())
);


-- ─── Part II configuration: stock items ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.stock_items (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text        NOT NULL,
  unit       text        NOT NULL,
  position   integer     NOT NULL CHECK (position > 0),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);


-- ─── Part III configuration: open sections ───────────────────────────────────

CREATE TABLE IF NOT EXISTS public.report_sections (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text        NOT NULL,
  position   integer     NOT NULL CHECK (position > 0),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);


-- ─── Reports (one per shift) ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.reports (
  id           bigint               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id     bigint               NOT NULL UNIQUE REFERENCES public.shifts(id) ON DELETE RESTRICT,
  status       public.report_status NOT NULL DEFAULT 'in_progress',
  created_at   timestamptz          NOT NULL DEFAULT timezone('utc', now()),
  submitted_at timestamptz,
  submitted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- submitted_at must be present iff status is completed.
  -- submitted_by may be NULL even on completed reports (user was deleted after submission).
  CONSTRAINT reports_submitted_consistency CHECK (
    (status = 'in_progress' AND submitted_at IS NULL) OR
    (status = 'completed'   AND submitted_at IS NOT NULL)
  )
);

-- Wire up the pre-existing shifts.report_id column (plain bigint, no FK until now)
ALTER TABLE public.shifts
  ADD CONSTRAINT shifts_report_id_fkey
  FOREIGN KEY (report_id) REFERENCES public.reports(id)
  ON DELETE SET NULL;


-- ─── Part I snapshot + completions ───────────────────────────────────────────

-- Snapshot of task template items taken at report creation.
-- Stores text directly — NOT a FK to task_template_items — so changes to the
-- live template never affect in-progress or completed reports.
CREATE TABLE IF NOT EXISTS public.report_task_items (
  id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id   bigint  NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  position    integer NOT NULL CHECK (position > 0),
  description text    NOT NULL
);

-- One row per completed task. A task with no row is incomplete.
-- Deleting the row marks the task unchecked (toggle pattern).
-- completed_by uses SET NULL so historical completions survive user deletion.
CREATE TABLE IF NOT EXISTS public.report_task_completions (
  id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_item_id bigint      NOT NULL UNIQUE REFERENCES public.report_task_items(id) ON DELETE CASCADE,
  completed_by uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  completed_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);


-- ─── Part II snapshot + entries ──────────────────────────────────────────────

-- Snapshot of stock items taken at report creation.
-- Stores name and unit as text — same snapshot rationale as above.
CREATE TABLE IF NOT EXISTS public.report_stock_items (
  id        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id bigint  NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  position  integer NOT NULL CHECK (position > 0),
  name      text    NOT NULL,
  unit      text    NOT NULL
);

-- One row per stock snapshot item. A missing row means the bartender has not
-- yet entered a value. All items must have an entry before submission is allowed
-- (enforced at application layer — DB allows null quantity until submission).
CREATE TABLE IF NOT EXISTS public.report_stock_entries (
  id            bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_item_id bigint  NOT NULL UNIQUE REFERENCES public.report_stock_items(id) ON DELETE CASCADE,
  quantity      numeric,
  not_relevant  boolean NOT NULL DEFAULT false,

  -- Either a quantity is provided, or the item is marked not relevant.
  -- Both fields may be null/false while the report is in_progress.
  -- Application must enforce all items are resolved before allowing submission.
  CONSTRAINT report_stock_entries_value_check CHECK (
    not_relevant = true OR quantity IS NOT NULL
  )
);


-- ─── Part III snapshot + responses ───────────────────────────────────────────

-- Snapshot of open sections taken at report creation.
CREATE TABLE IF NOT EXISTS public.report_section_items (
  id        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id bigint  NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  position  integer NOT NULL CHECK (position > 0),
  name      text    NOT NULL
);

-- Free-text responses. response is nullable — Part III is entirely optional
-- and no section response gates submission.
CREATE TABLE IF NOT EXISTS public.report_section_responses (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_item_id bigint NOT NULL UNIQUE REFERENCES public.report_section_items(id) ON DELETE CASCADE,
  response        text
);


-- ─── Indexes ─────────────────────────────────────────────────────────────────

-- task_template_items: loading items by template
CREATE INDEX idx_task_template_items_template_id ON public.task_template_items (template_id);

-- report_* snapshot tables: loading all items for a report
CREATE INDEX idx_report_task_items_report_id     ON public.report_task_items    (report_id);
CREATE INDEX idx_report_stock_items_report_id    ON public.report_stock_items   (report_id);
CREATE INDEX idx_report_section_items_report_id  ON public.report_section_items (report_id);

-- report_task_completions: audit queries by user
CREATE INDEX idx_report_task_completions_completed_by ON public.report_task_completions (completed_by);

-- reports: lookup by submitter (manager audit view)
CREATE INDEX idx_reports_submitted_by ON public.reports (submitted_by);


-- ─── Grants ──────────────────────────────────────────────────────────────────

GRANT ALL ON TABLE public.task_templates             TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.task_template_items        TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.stock_items                TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.report_sections            TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.reports                    TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.report_task_items          TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.report_task_completions    TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.report_stock_items         TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.report_stock_entries       TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.report_section_items       TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.report_section_responses   TO anon, authenticated, service_role;

GRANT ALL ON SEQUENCE public.task_templates_id_seq             TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.task_template_items_id_seq        TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.stock_items_id_seq                TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.report_sections_id_seq            TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.reports_id_seq                    TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.report_task_items_id_seq          TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.report_task_completions_id_seq    TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.report_stock_items_id_seq         TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.report_stock_entries_id_seq       TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.report_section_items_id_seq       TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.report_section_responses_id_seq   TO anon, authenticated, service_role;
