-- Migration: 20260328000000_add_shift_assignments.sql
-- Description: Introduces the shift_assignments join table to replace shifts.bartenders JSONB.
--   Creates the table, backfills from existing JSONB data, and adds grants.
--
--   The bartenders column is intentionally NOT dropped here. See the companion migration
--   20260328000001_drop_shifts_bartenders.sql, which is applied separately in production
--   after the updated application code has been deployed and verified (see deployment brief
--   docs/devops/TSK-SHF-020-deployment.md).
--
--   For local dev and CI, both migrations are applied in sequence by supabase db reset,
--   so the final state is correct in all environments.
--
-- Rollback (before companion migration has run):
--   DROP INDEX IF EXISTS idx_shift_assignments_user_id;
--   DROP TABLE IF EXISTS public.shift_assignments;


-- 1. Create the join table
CREATE TABLE IF NOT EXISTS public.shift_assignments (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id   bigint      NOT NULL REFERENCES public.shifts(id) ON DELETE CASCADE,
  user_id    uuid        NOT NULL REFERENCES auth.users(id)     ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT shift_assignments_shift_user_unique UNIQUE (shift_id, user_id)
);


-- 2. Backfill from existing JSONB data.
--    Orphaned UUIDs (belonging to users deleted from auth.users) are silently
--    skipped via the EXISTS filter — they cannot satisfy the FK constraint.
--    created_at is approximated from the parent shift's created_at because
--    individual signup timestamps were not recorded in the JSONB model.
INSERT INTO public.shift_assignments (shift_id, user_id, created_at)
SELECT
  s.id,
  elem::uuid,
  s.created_at
FROM
  public.shifts s,
  jsonb_array_elements_text(s.bartenders) AS elem
WHERE
  jsonb_array_length(s.bartenders) > 0
  AND EXISTS (SELECT 1 FROM auth.users u WHERE u.id = elem::uuid)
ON CONFLICT (shift_id, user_id) DO NOTHING;


-- 3. Indexes
--    The UNIQUE constraint on (shift_id, user_id) already provides an index that
--    Postgres can use for shift_id-only lookups (leftmost column).
--    A separate index on user_id is needed for "all shifts for user X" queries.
CREATE INDEX idx_shift_assignments_user_id ON public.shift_assignments (user_id);


-- 4. Grants — match the permission pattern of all other tables in this schema
GRANT ALL ON TABLE    public.shift_assignments            TO anon;
GRANT ALL ON TABLE    public.shift_assignments            TO authenticated;
GRANT ALL ON TABLE    public.shift_assignments            TO service_role;

GRANT ALL ON SEQUENCE public.shift_assignments_id_seq    TO anon;
GRANT ALL ON SEQUENCE public.shift_assignments_id_seq    TO authenticated;
GRANT ALL ON SEQUENCE public.shift_assignments_id_seq    TO service_role;
